# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, glibc
, stdenv.cc.cc.lib
, makeWrapper
}:
let
  shaMap = {
    x86_64-linux = "1p2v3hr5q2s5iwd44lxj94zcnh4cf5v7y6cbdn2bdyqag7my0awc";
    aarch64-linux = "13kwbnsl7zymc80pviln5asb53pi1gyymxfvdxsra1fksh5fj7ya";
    x86_64-darwin = "0ky5xj8f6xfsxmk8w9gh5k8iywl4qrhmsdfp1jzrfpryrxw4ikr9";
    aarch64-darwin = "0zfk7184p9qi02bh8i2swldwa6jszvhin6y9giafz5gmllmxw2gw";
  };

  urlMap = {
    x86_64-linux = "https://github.com/sonr-io/sonr/releases/download/hway%2Fv0.0.3/hway_linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/sonr-io/sonr/releases/download/hway%2Fv0.0.3/hway_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/sonr-io/sonr/releases/download/hway%2Fv0.0.3/hway_darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/sonr-io/sonr/releases/download/hway%2Fv0.0.3/hway_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hway";
  version = "0.0.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./hway $out/bin/hway
    wrapProgram $out/bin/hway --prefix PATH : ${lib.makeBinPath ([ glibc stdenv.cc.cc.lib ])}
  '';

  system = system;

  meta = {
    description = "Highway network component for Sonr";
    homepage = "https://sonr.io";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
