# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, glibc
, stdenv.cc.cc.lib
, makeWrapper
}:
let
  shaMap = {
    x86_64-linux = "0xrlhbxsc9p41jxwq1ywypjb9m80kgaq7z5b3v672qj47wkjwvfa";
    aarch64-linux = "0s808sgnffccqf0sf6lq6c7ppkd5q0x7jj7gv3nk376s7alz0f3g";
    x86_64-darwin = "102l593mfh0w1bzqxk6jyqcgwsygzi0q3viqmh9w4kvnw3gvvjym";
    aarch64-darwin = "1k9fy051xkk1c1cbszymzv9qghshzk9lp1y92yqkx39zlzydjr07";
  };

  urlMap = {
    x86_64-linux = "https://github.com/sonr-io/sonr/releases/download/hway%2Fv0.0.4/hway_linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/sonr-io/sonr/releases/download/hway%2Fv0.0.4/hway_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/sonr-io/sonr/releases/download/hway%2Fv0.0.4/hway_darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/sonr-io/sonr/releases/download/hway%2Fv0.0.4/hway_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hway";
  version = "0.0.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./hway $out/bin/hway
    wrapProgram $out/bin/hway --prefix PATH : ${lib.makeBinPath ([ glibc stdenv.cc.cc.lib ])}
  '';

  system = system;

  meta = {
    description = "Highway network component for Sonr";
    homepage = "https://sonr.io";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
