# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, stdenv
, glibc
, makeWrapper
}:
let
  shaMap = {
    x86_64-linux = "14vjmfdpbj9ins08mzaxv339r63d1hv8zsyhczkh8ljcpgrjrfx4";
    aarch64-linux = "1y7s9m2pk7nkfwnp8ghdbb3x6ri8m1v4207yy350kcv1land2l9n";
    x86_64-darwin = "1fms15nfkxhvn8bf0rs77pfwxpfrhkq6j7cg8gzjkjzp40b6yabm";
    aarch64-darwin = "00av4499kww8pch6nbx5wsjidaifmixf8yvc5hhxnm1r0yc28wyd";
  };

  urlMap = {
    x86_64-linux = "https://github.com/sonr-io/sonr/releases/download/snrd/v0.0.1/snrd_linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/sonr-io/sonr/releases/download/snrd/v0.0.1/snrd_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/sonr-io/sonr/releases/download/snrd/v0.0.1/snrd_darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/sonr-io/sonr/releases/download/snrd/v0.0.1/snrd_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "snrd";
  version = "0.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./snrd $out/bin/snrd
    wrapProgram $out/bin/snrd --prefix PATH : ${lib.makeBinPath ([ glibc stdenv.cc.cc.lib ])}
  '';

  system = system;

  meta = {
    description = "Sonr blockchain daemon - decentralized identity network";
    homepage = "https://sonr.io";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
