# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, stdenv
, glibc
, makeWrapper
}:
let
  shaMap = {
    x86_64-linux = "1bw4j38xljr6sqfnxxzpz7xknjiig8lisrnhj9gc8znln3ni2a2k";
    aarch64-linux = "1xqsh8pfc3xsjzk5g0lwwwap99szsd10az8c3wgifhdn4c5fc7yf";
    x86_64-darwin = "0wmwfik41bjsfcgv6dh2vk80gf4vjxxfflwdlap49qxb9gay5g16";
    aarch64-darwin = "1zwpjsynhv0djpqwzcks0b6q6pb9ba4r085ag69yg5rhkd7570k1";
  };

  urlMap = {
    x86_64-linux = "https://github.com/sonr-io/sonr/releases/download/snrd%2Fv0.0.2/snrd_linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/sonr-io/sonr/releases/download/snrd%2Fv0.0.2/snrd_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/sonr-io/sonr/releases/download/snrd%2Fv0.0.2/snrd_darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/sonr-io/sonr/releases/download/snrd%2Fv0.0.2/snrd_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "snrd";
  version = "0.0.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./snrd $out/bin/snrd
    wrapProgram $out/bin/snrd --prefix PATH : ${lib.makeBinPath ([ stdenv glibc ])}
    wrapProgram $out/bin/snrd --prefix PATH : ${lib.makeBinPath [ glibc stdenv.cc.cc.lib ]}
  '';

  system = system;

  meta = {
    description = "Sonr blockchain daemon - decentralized identity network";
    homepage = "https://sonr.io";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
