# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, glibc
, stdenv.cc.cc.lib
, makeWrapper
}:
let
  shaMap = {
    x86_64-linux = "0dmz1v44mp8nx3wz2mw6r5rh2xpggz7x7pdgv4y3lz8j2ly43y70";
    aarch64-linux = "0b2i9qma25g69g1gwxga0qva0gidczc5pn32sbdnvywbwlklm3mq";
    x86_64-darwin = "1p6fb9xh81gsql4ayb6jfvjlvn19f8m2xwj3wkn3wczp6km3b2k2";
    aarch64-darwin = "14ai9z27sgkjfvkficlbj1s5rkwm09q9r5n3zmdwscj8l53vkyi3";
  };

  urlMap = {
    x86_64-linux = "https://github.com/sonr-io/sonr/releases/download/snrd%2Fv0.0.1/snrd_linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/sonr-io/sonr/releases/download/snrd%2Fv0.0.1/snrd_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/sonr-io/sonr/releases/download/snrd%2Fv0.0.1/snrd_darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/sonr-io/sonr/releases/download/snrd%2Fv0.0.1/snrd_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "snrd";
  version = "0.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./snrd $out/bin/snrd
    wrapProgram $out/bin/snrd --prefix PATH : ${lib.makeBinPath ([ glibc stdenv.cc.cc.lib ])}
  '';

  system = system;

  meta = {
    description = "Sonr blockchain daemon - decentralized identity network";
    homepage = "https://sonr.io";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
